---
title: "eda"
output: pdf_document
date: "2026-03-24"
---

```{r}
library(tidyverse)
library(haven)
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)

# TREATMENT - pesticide (PUBMEC_L) 

# COVARIATES - alcohol use (ALQ_L), demographics (DEMO_L), diabetes (DIQ_L), 
# cholesterol (TCHOL_L),  income (INQ_L), physical activity (PAQ_L), 
# sleep (SLQ), smoking (SMQ), weight (WHQ_L) 

# RESPONSE - blood pressure (BPXO_L) 
```

## treatment / response

```{r}
pesticide <- read_xpt("Data/PUQMEC_L.xpt")
blood_pressure <- read_xpt("Data/BPXO_L.xpt")
```

```{r}
invalid <- c(7, 9, 77, 99, 777, 999, 7777, 9999, NA, "") 
pesticide$PUQ100 <- ifelse(pesticide$PUQ100 %in% invalid, NA, pesticide$PUQ100)
pesticide$PUQ110 <- ifelse(pesticide$PUQ110 %in% invalid, NA, pesticide$PUQ110)

data <- pesticide %>%
  inner_join(blood_pressure, by = "SEQN") %>%
  rename (
    insecticide = PUQ100, 
    weed_killers = PUQ110,
    
    
    # Systolic readings
    systolic_1 = BPXOSY1,
    systolic_2 = BPXOSY2,
    systolic_3 = BPXOSY3,
    
    # Diastolic readings
    diastolic_1 = BPXODI1,
    diastolic_2 = BPXODI2,
    diastolic_3 = BPXODI3,
    
    # Pulse readings
    pulse_1 = BPXOPLS1,
    pulse_2 = BPXOPLS2,
    pulse_3 = BPXOPLS3
  ) %>%
  
  mutate(insecticide = recode(insecticide,
                            `1` = 1,
                            `2` = 0),
         weed_killers = recode(weed_killers,
                            `1` = 1,
                            `2` = 0))
```


```{r}
table(data$insecticide, useNA = "always")
table(data$weed_killers, useNA = "always")
```

```{r}
trt_response <- data %>%
  mutate(
    systolic_avg = rowMeans(select(., systolic_1, systolic_2, systolic_3), na.rm = TRUE),
    diastolic_avg = rowMeans(select(., diastolic_1, diastolic_2, diastolic_3), na.rm = TRUE),
    pulse_avg = rowMeans(select(., pulse_1, pulse_2, pulse_3), na.rm = TRUE)) %>%
  
  select(SEQN, #unique id
         insecticide, weed_killers, #treatment(s) 
         systolic_avg, diastolic_avg, #response(s)
         pulse_avg) #covariate
```



## add covariates

```{r}
DEMO_L <- read_xpt("Data/DEMO_L.xpt")
ALQ_L <- read_xpt("Data/ALQ_L.xpt")
DIQ_L <- read_xpt("Data/DIQ_L.xpt")
TCHOL_L <- read_xpt("Data/TCHOL_L.xpt")
INQ_L <- read_xpt("Data/INQ_L.xpt")
PAQ_L <- read_xpt("Data/PAQ_L.xpt")
SLQ_L <- read_xpt("Data/SLQ_L.xpt")
SMQ_L <- read_xpt("Data/SMQ_L.xpt")
WHQ_L <- read_xpt("Data/WHQ_L.xpt")
```

```{r}
clean_df <- trt_response %>%
  
  #join other covariates 
  left_join(DEMO_L, by = "SEQN") %>% #demographics
  left_join(ALQ_L, by = "SEQN") %>% #alcohol
  left_join(DIQ_L, by = "SEQN") %>% #diabetes
  left_join(TCHOL_L, by = "SEQN") %>% #cholesterol 
  left_join(INQ_L, by = "SEQN") %>% #income
  left_join(PAQ_L, by = "SEQN") %>% #physical activity 
  left_join(SLQ_L, by = "SEQN") %>% #sleep disorders 
  left_join(SMQ_L, by = "SEQN") %>% #smoking
  left_join(WHQ_L, by = "SEQN") %>% #weight
         
  select(insecticide, weed_killers, #treatment(s)
         systolic_avg, diastolic_avg, #response(s)
         pulse_avg, #covariates
         RIAGENDR, RIDAGEYR, RIDRETH1, RIDRETH3, DMQMILIZ, DMDBORN4, DMDYRUSR,
         DMDEDUC2, DMDMARTZ, DMDHHSIZ, DMDHRGND, INDFMPIR, ALQ130, 
         DIQ010, LBXTC, DID040, INDFMMPC, PAD790Q, PAD790U, PAD810Q, PAD810U, PAD680,
         SLD012, SLD013, SMQ020, SMD650, WHD010, WHD020, WHD050
         ) %>%

  rename(
    # ---------------- DEMO ----------------
    gender = RIAGENDR,
    age_years = RIDAGEYR,
    race_ethnicity = RIDRETH1,
    race_ethnicity_detailed = RIDRETH3,
    active_duty_military = DMQMILIZ,
    country_of_birth = DMDBORN4,
    years_in_us = DMDYRUSR,
    education_level = DMDEDUC2,
    marital_status = DMDMARTZ,
    household_size = DMDHHSIZ,
    hh_reference_gender = DMDHRGND,
    income_poverty_ratio = INDFMPIR,
    # ---------------- ALQ (Alcohol) ----------------
    alcohol_avg_drinks_per_day = ALQ130,
    # ---------------- DIQ (Diabetes) ----------------
    diabetes_diagnosed = DIQ010,
    age_diabetes_diagnosed = DID040,
    # ---------------- TCHOL (Cholesterol) ----------------
    tot_cholesterol = LBXTC,  
    # ---------------- INQ (Income) ----------------
    monthly_poverty_category = INDFMMPC,
    # ---------------- PAQ (Physical Activity) ----------------
    mod_activity_freq = PAD790Q,
    mod_activity_unit = PAD790U,
    vig_activity_freq = PAD810Q,
    vig_activity_unit = PAD810U,
    sedentary_minutes = PAD680,
    # ---------------- SLQ (Sleep) ----------------
    sleep_hours_weekday = SLD012,
    sleep_hours_weekend = SLD013,
    # ---------------- SMQ (Smoking) ----------------
    smoked_100_cigs = SMQ020,
    cig_per_day = SMD650,
    # ---------------- WHQ (Weight/Height) ----------------
    height_inches = WHD010,
    weight_pounds = WHD020,
    weight_1yr_ago = WHD050
    ) 
```

```{r}
invalid <- c(7, 9, 77, 99, 777, 999, 7777, 9999, NA, "") 

#recode variables 
clean_df <- clean_df %>%
  mutate(
    pesticides = insecticide | weed_killers,
    
    gender = recode(gender, `1` = "Male", `2` = "Female"),
    race_ethnicity = recode(race_ethnicity,
                            `1` = "Mexican American",
                            `2` = "Other Hispanic",
                            `3` = "Non-Hispanic White",
                            `4` = "Non-Hispanic Black",
                            `5` = "Other Race"),
    race_ethnicity_detailed = recode(race_ethnicity_detailed,
                                     `1` = "Mexican American",
                                     `2` = "Other Hispanic",
                                     `3` = "Non-Hispanic White",
                                     `4` = "Non-Hispanic Black",
                                     `6` = "Non-Hispanic Asian",
                                     `7` = "Other Race"),
    active_duty_military = recode(active_duty_military, `1` = 1, `2` = 0, `7` = NA_real_),
    
    born_in_US = recode(country_of_birth, `1` = 1, `2` = 0, `77` = NA_real_,
                              `99` = NA_real_),
    
    years_in_us = recode(years_in_us,
                             `1` = "<1 year",
                             `2` = "1-4 years",
                             `3` = "5-9 years",
                             `4` = "10-14 years",
                             `5` = "15-19 years",
                             `6` = "20+ years",
                             `77` = NA_character_,
                             `99` = NA_character_),
    
    
    education_level = recode(education_level,
                             `1` = "<9th grade",
                             `2` = "9-11th grade",
                             `3` = "High school/GED",
                             `4` = "Some college/AA",
                             `5` = "College graduate or above",
                             `9` =  NA_character_), 
    marital_status = recode(marital_status,
                            `1` = "Married",
                            `2` = "Widowed",
                            `3` = "Divorced",
                            `77` = NA_character_,
                            `99` = NA_character_),
    hh_reference_gender = recode(hh_reference_gender, `1` = "Male", `2` = "Female"),
    
    alcohol_avg_drinks_per_day = if_else(alcohol_avg_drinks_per_day %in% c(777, 999), 
                                         NA_real_, alcohol_avg_drinks_per_day),
    
    diabetes_diagnosed = recode(diabetes_diagnosed, `1` = 1, 
                                                    `2` = 0, 
                                                    `3` = NA_real_, `7` = NA_real_, `9` = NA_real_),
    
    age_diabetes_diagnosed = ifelse(age_diabetes_diagnosed %in% invalid, NA, age_diabetes_diagnosed),
    
    monthly_poverty_category = recode(monthly_poverty_category, 
                                      `1` = "Low",
                                      `2` = "Medium",
                                      `3` = "High",
                                      `7` = NA_character_, `9` = NA_character_),
    
   
    mod_activity_unit = ifelse(mod_activity_unit %in% invalid, NA_real_,
                               recode(mod_activity_unit, `D` = 7, `W` = 1, 
                                      `M` = (1/4.345), `Y` = (1 / 52.143), .default = NA_real_)),
    mod_activity_per_week = ifelse(mod_activity_freq %in% c(NA, 7777, 9999), 
                                    NA_real_,
                                    mod_activity_freq * mod_activity_unit),
    
    
    vig_activity_unit = ifelse(vig_activity_unit %in% invalid, NA_real_,
                               recode(vig_activity_unit, `D` = 7, `W` = 1, 
                                      `M` = (1/4.345), `Y` = (1 / 52.143), .default = NA_real_)),
    
    vig_activity_per_week = ifelse(vig_activity_freq %in% c(NA, 7777, 9999), 
                                   NA_real_,
                                   vig_activity_freq * vig_activity_unit),
    
    
    sedentary_minutes = if_else(sedentary_minutes %in% c(7777, 9999), 
                                         NA_real_, sedentary_minutes),
    
    smoked_100_cigs = recode(smoked_100_cigs, `1` = 1, `2` = 0, `7` = NA_real_, `9` = NA_real_),
    cig_per_day = if_else(cig_per_day %in% c(777, 999), NA_real_, cig_per_day),
    
    height_inches = if_else(height_inches %in% c(7777, 9999), NA_real_, height_inches),
    weight_pounds = if_else(weight_pounds %in% c(7777, 9999), NA_real_, weight_pounds),
    weight_1yr_ago = if_else(weight_1yr_ago %in% c(7777, 9999), NA_real_, weight_1yr_ago))  %>%

  select(-country_of_birth, -mod_activity_freq, -mod_activity_unit, 
         -vig_activity_freq, -vig_activity_unit)

```

```{r}
write.csv(clean_df, "Data/clean_df.csv")
```

## EDA

```{r}
par(mfrow = c(1, 2))

# Systolic
hist(clean_df$systolic_avg,
     main = "Distribution of Systolic Blood Pressure",
     xlab = "Systolic BP (mmHg)",
     col = "skyblue",
     border = "white",
     breaks = 20)

# Diastolic
hist(clean_df$diastolic_avg,
     main = "Distribution of Diastolic Blood Pressure",
     xlab = "Diastolic BP (mmHg)",
     col = "salmon",
     border = "white",
     breaks = 20)
```

```{r}
df_counts <- clean_df %>%
  mutate(group = case_when(
    insecticide == 1 & weed_killers == 1 ~ "insecticides and weed killers",
    insecticide == 1 & weed_killers == 0 ~ "insecticides",
    insecticide == 0 & weed_killers == 1 ~ "weed killers",
    TRUE ~ "neither"
  )) %>%
  count(group)

ggplot(df_counts, aes(x = "", y = n, fill = group)) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y") +  
  labs(y = "Count", x = "") +
  theme_minimal()
```

```{r}
na_counts <- sapply(clean_df, function(x) sum(is.na(x)))
na_counts
```
```{r}
summary(clean_df)


```

```{r}
hist(clean_df$mod_activity_per_week)
```

```{r}
library(devtools)
install_github("haleyjeppson/ggmosaic")
library(ggmosaic)
mosiac = (clean_df %>%
    select(c(gender, insecticide))) %>%
    drop_na(gender, insecticide)

ggplot(data = mosiac) + geom_mosaic(aes(x = product(insecticide), fill = gender))

```

```{r}
wls_2_rand = clean_df %>%
    mutate(insecticide = sample(insecticide))
wls_2num_g = melt(wls_2_rand %>%
    select(c(insecticide, age_years, income_poverty_ratio, 
             alcohol_avg_drinks_per_day, tot_cholesterol)), id.var = "insecticides")
ggplot(data = wls_2num_g, aes(x = variable, y = value)) + geom_boxplot(aes(fill = insecticide)) +
    facet_wrap(~variable, scales = "free")
```