---
title: "Hearing_Score_Analysis"
output: pdf_document
date: "2026-04-01"
---

# Hearing Score
```{r}
library(tidyverse)
library(dplyr)
```

```{r}
clean_df <- read_csv("/Users/carolinemoy/stats571finalproj/Data/clean_df.csv")
```
```{r}
freq_table <- table(clean_df$hearing_cond, clean_df$insecticide)
prop.table(freq_table, margin = 2)
```
```{r}
table(clean_df$hearing_cond)
```

```{r}
clean_df <- clean_df %>% 
  mutate(deaf = ifelse(hearing_cond == "Deaf", 1, 0), 
         excellent = ifelse(hearing_cond == "Excellent", 1, 0), 
         good = ifelse(hearing_cond == "Good", 1, 0), 
         little_trouble = ifelse(hearing_cond == "A Little Trouble", 1, 0), 
         lot_trouble = ifelse(hearing_cond == "Lot of Trouble", 1, 0), 
         moderate_trouble = ifelse(hearing_cond == "Moderate Trouble", 1, 0), 
         hearing_cond = factor(hearing_cond, levels = c("Excellent", 
                                                        "Good", 
                                                        "A Little Trouble", 
                                                        "Moderate Trouble", 
                                                        "Lot of Trouble", 
                                                        "Deaf")))
```

```{r}
hearing_conditions <- c("excellent", 
  "good", 
  "little_trouble", 
  "moderate_trouble",
  "lot_trouble", 
  "deaf")

p_val_vec <- unlist(lapply(hearing_conditions, function(col) {
  result <- t.test(
    clean_df[clean_df$insecticide == 1, ][[col]],
    clean_df[clean_df$insecticide == 0, ][[col]]
  )
  result$p.value
}))
```

```{r}
hearing_conditions_df <- data.frame(hearing_conditions, p_val_vec)
```

```{r}
hearing_conditions_df %>% 
  mutate(significant_diff = ifelse(p_val_vec < 0.05, TRUE, FALSE))
```

# Checking Income and Hearing Condition 
```{r}
c("Excellent", "Good", 
                                                        "A Little Trouble", 
                                                        "Moderate Trouble", 
                                                        "Lot of Trouble", 
                                                        "Deaf")

p_val_vec_income <- unlist(lapply(hearing_conditions, function(col) {
  result <- t.test(
    clean_df[clean_df$hearing_cond == col, ][[col]],
    clean_df[clean_df$insecticide == col, ][[col]]
  )
  result$p.value
}))
```

